version: '2'

services:

  kafka_ctl_1:
    image: bitnami/kafka:latest
    hostname: kafka_ctl_1
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_KRAFT_CLUSTER_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller
      - KAFKA_CFG_LISTENERS=CONTROLLER://:${CONTROLLER_PORT},
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka_ctl_1:${CONTROLLER_PORT},1@kafka_ctl_2:${CONTROLLER_PORT},2@kafka_ctl_3:${CONTROLLER_PORT}
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - ${CONTROLLER_PORT}
  
  kafka_ctl_2:
    image: bitnami/kafka:latest
    hostname: kafka_ctl_2
    depends_on:
      - kafka_ctl_1
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller
      - KAFKA_CFG_LISTENERS=CONTROLLER://:${CONTROLLER_PORT},
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka_ctl_1:${CONTROLLER_PORT},1@kafka_ctl_2:${CONTROLLER_PORT},2@kafka_ctl_3:${CONTROLLER_PORT}
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - ${CONTROLLER_PORT}
  
  kafka_ctl_3:
    image: bitnami/kafka:latest
    hostname: kafka_ctl_3
    depends_on:
      - kafka_ctl_1
      - kafka_ctl_2
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_KRAFT_CLUSTER_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller
      - KAFKA_CFG_LISTENERS=CONTROLLER://:${CONTROLLER_PORT},
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka_ctl_1:${CONTROLLER_PORT},1@kafka_ctl_2:${CONTROLLER_PORT},2@kafka_ctl_3:${CONTROLLER_PORT}
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - ${CONTROLLER_PORT}

  kafka_broker_1:
    image: bitnami/kafka:latest
    hostname: kbroker1
    depends_on:
      - kafka_ctl_1
      - kafka_ctl_2
      - kafka_ctl_3
    environment:
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_KRAFT_CLUSTER_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:${BROKER_PORT},
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kbroker1:${BROKER_PORT},
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka_ctl_1:${CONTROLLER_PORT},1@kafka_ctl_2:${CONTROLLER_PORT},2@kafka_ctl_3:${CONTROLLER_PORT}
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - ${BROKER_PORT}

  consumer:
    build:
      context:
        ./
    volumes:
      - ../:/kafka_ex/
    env_file: ../.env
    command: >
      bash -c "sleep 20 && python app/consumer.py"
    depends_on:
      - kafka_broker_1

  producer:
    build:
      context:
        ./
    volumes:
      - ../:/kafka_ex/
    env_file: ../.env
    command: >
      bash -c "sleep 20 && python app/producer.py"
    depends_on:
      - kafka_broker_1
      - consumer
